FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]

# docker build -f Dockerfile.dev .
# delete local node modules folder
# docker run -p 3000:3000 <image>
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app <image>
# docker run -it <image> npm run test